version: '3.8'

services:
  database:
    container_name: database
    image: postgres:15.3-alpine3.18
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    ports:
      - "5432:5432"
